enabled: true
top_level_version: true
home_url: 'http://matchavez.com'
github:
  position: 'off'
default_taxonomy_category: docs
style: spitsbergen
streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': [user/themes/learn2-git-sync, user/themes/learn2]
hide_site_title: false
