enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: true
header-transparent: true
sticky-footer: false
blog-page: /blog
spectre:
  exp: true
  icons: true
