title: SouthIslander.com
default_lang: en
author:
  name: Southie
  email: john@email.com
taxonomies:
  - category
  - tag
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
