title: MatChavez.com
default_lang: en
author:
  name: Mat
  email: matchavez@icloud.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Mat Chavez'
summary:
  enabled: false
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
